### ISSUE TITLE
Postgres: add ColumnExpression `BigSerial` and `SmallSerial`

### ISSUE THREAD

**Issue by gfoidl** [JasperFx/weasel#76]
There's a column expression for `Serial` https://github.com/JasperFx/weasel/blob/17951b8a57e968dff15c3c07ecfcaad2a8b49255/src/Weasel.Postgresql/Tables/Table.cs#L391, but as Postgres supports more [serial types](https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-SERIAL) there should be expression for these too -- at least for `bigserial`.

<sub>I can submit PR if the additon is approved.</sub>

**Comment by gfoidl** [comment]
More info why it's needed...

With Marten a column can be created with
```c#
myTable.AddColumn("id", "bigserial").AsPrimaryKey();

// ...
await store.Storage.ApplyAllConfiguredChangesToDatabaseAsync();
```
the the table gets created as expected, with Postgres creating the column with `bigint` and setting up the sequence.
But in the next run Marten (actually: Weasel) tries to update the column-definition from _bigint_ to _bigserial_ which results in an exception:
```
alter table public.XYZ alter column position type bigserial;

Unhandled exception. Marten.Exceptions.MartenSchemaException: DDL Execution for 'All Configured Changes' Failed!

alter table public.XYZ alter column position type bigserial;

 ---> Npgsql.PostgresException (0x80004005): 42704: type "bigserial" does not exist
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|213_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Weasel.Postgresql.PostgresqlMigrator.executeDelta(SchemaMigration migration, DbConnection conn, AutoCreate autoCreate, IMigrationLogger logger)
  Exception data:
    Severity: ERROR
    SqlState: 42704
    MessageText: type "bigserial" does not exist
    File: parse_type.c
    Line: 270
    Routine: typenameType
```

So my naive assumption is that when `BigSerial` column-expression is supported, that use-case should work.

**Comment by oskardudycz** [comment]
Sounds right. Are you open to contributing to adding that?

**Comment by gfoidl** [comment]
Yep, I'll create a PR.

**Comment by oskardudycz** [comment]
Thank you :heart:
